---
- hosts: newrelic_agent_os_linux:newrelic_agent_os_windows
  # gather_facts: yes
  # become: yes
  roles:
    - name: newrelic.newrelic-infra
      vars:
        log_file: /opt/logs/newrelic-infra.log
        verbose: 0
        nrinfragent_config:
          license_key: "{{ newrelic_license_key }}"
          custom_attributes:
            environment: dev